# mysql 配置
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: jishuzhai
  db_name: rust_book
  #最小连接数
  pool_min_idle: 8
  #最大连接数
  pool_max_open: 32
  #连接超时时间单位秒
  timeout_seconds: 15